# Generated by Django 5.1 on 2025-01-06 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseteacher'),
        ('institutions', '0002_alter_institutions_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.AddField(
            model_name='classroom',
            name='enrollments',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(default=0, limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classrooms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutions.institutions'),
        ),
        migrations.DeleteModel(
            name='CourseTeacher',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
