# Generated by Django 5.1 on 2025-04-29 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0002_theoryquestions_marks_theorysubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theorysubmission',
            name='answers',
        ),
        migrations.AddField(
            model_name='theorysubmissionanswer',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theoryquestions',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theorysubmission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theorysubmissionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='theory.theoryquestions'),
        ),
        migrations.AlterField(
            model_name='theorysubmissionanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='theory.theorysubmission'),
        ),
    ]
