# Generated by Django 5.1 on 2025-04-29 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0003_remove_theorysubmission_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoryquestions',
            name='answer_type',
            field=models.CharField(choices=[('short', 'Short'), ('long', 'Long'), ('paraphrased', 'Paraphrased')], default='short', max_length=255),
        ),
        migrations.CreateModel(
            name='PlagiarismRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('similarity_score', models.FloatField()),
                ('submission1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_as_submission1', to='theory.theorysubmission')),
                ('submission2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_as_submission2', to='theory.theorysubmission')),
            ],
            options={
                'unique_together': {('submission1', 'submission2')},
            },
        ),
    ]
