# Generated by Django 5.1 on 2025-05-11 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0004_theoryquestions_answer_type_plagiarismrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarismrecord',
            name='threshold_used',
            field=models.FloatField(default=0.85),
        ),
        migrations.AddField(
            model_name='theorysubmission',
            name='plagiarism_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuestionPlagiarismRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('similarity_score', models.FloatField()),
                ('plagiarism_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_records', to='theory.plagiarismrecord')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_records', to='theory.theoryquestions')),
            ],
            options={
                'unique_together': {('plagiarism_record', 'question')},
            },
        ),
    ]
