# Generated by Django 5.1 on 2025-01-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_enrollment_classroom_and_more'),
        ('omr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omr',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='omr',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.classroom'),
        ),
    ]
