# Generated by Django 5.1 on 2025-01-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0002_remove_omr_teacher_alter_omr_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrquestions',
            name='omr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='omr.omr'),
        ),
    ]
