# Generated by Django 5.1 on 2024-10-14 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_institution'),
        ('institutions', '0002_alter_institutions_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_user', to='institutions.institutions'),
        ),
    ]
